ying/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login
from django.views.generic import RedirectView

from ying import views

urlpatterns = [
    url(r'^accounts/login/$', login, {'template_name': 'chemist/login.html'}),
    # url(r'^accounts/edit$',
    #     views.account_edit,
    #     name="account_edit"),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^$', RedirectView.as_view(url='/movie/search', permanent=True), name='index'),

    url(r'^movie_folder$', views.MovieFolderListView.as_view()),

    url(r'^movie_folder/scan$', views.movie_scan),
    url(r'^movie_folder/no_movie$', views.FolderWithoutMovieListView.as_view(), name="folder_without_movie"),

    url(r'^movie_folder/detail/(?P<pk>[\w-]+)$', views.MovieFolderUpdateView.as_view(), name="folder_update"),
    url(r'^movie_folder/play/(?P<pk>[\w-]+)$', views.folder_play, name="folder_play"),


    url(r'^movie/detail/(?P<pk>[\w-]+)$', views.MovieDetailView.as_view(), name="movie_detail"),
    url(r'^movie/update/(?P<pk>[\w-]+)$', views.MovieUpdateView.as_view(), name="movie_update"),
    url(r'^movie/delete/(?P<pk>[\w-]+)$', views.MovieDeleteView.as_view(), name="movie_delete_confirm"),

    url(r'^movie/exist$', views.ExistMovieSearchListView.as_view(), name="movies_exist"),
    url(r'^movie/exist/g$', views.MovieSearchGalleryListView.as_view(), name="movies_exist_gallery"),
    url(r'^movie/search', views.MovieSearchListView.as_view(), name="movies_search"),

    url(r'^category$', views.CategoryListView.as_view()),
    url(r'^category/detail/(?P<pk>[\w-]+)$', views.CategoryUpdateView.as_view()),
]

ying/models.py
from django.db import models
from taggit.managers import TaggableManager
from sorl.thumbnail import ImageField


class Category(models.Model):
    name = models.CharField(max_length=50)
    tmdb_id = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=500)
    org_name = models.CharField(max_length=500)
    poster = ImageField(upload_to='movie_image')
    backdrop = ImageField(upload_to='movie_image')
    tmdb_id = models.IntegerField(blank=True, null=True)
    tmdb_popularity = models.FloatField(blank=True, null=True)
    tmdb_score = models.FloatField(blank=True, null=True)
    summary = models.TextField(max_length=5000, blank=True, null=True)
    year = models.IntegerField()
    category = models.ManyToManyField(Category)
    tags = TaggableManager(blank=True)
    comment = models.TextField(max_length=5000, blank=True, null=True)

    def __unicode__(self):
        encode_name = self.org_name.encode('ascii', 'ignore')
        if not encode_name:
            encode_name = self.name.encode('ascii', 'ignore')
        return '{}:{},{}'.format(self.tmdb_id, encode_name, self.year)


class MovieImage(models.Model):
    movie = models.ForeignKey(Movie)
    image = ImageField()
    image_type = models.IntegerField(blank=True, null=True)
    lang = models.CharField(max_length=20, blank=True, null=True)


class MovieFolder(models.Model):
    name = models.CharField(max_length=500)
    inode = models.CharField(max_length=20, null=True, blank=True)
    movie = models.ForeignKey(Movie, blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __unicode__(self):
        status = "[D]" if self.deleted else ""
        return status + self.name


class FolderVideo(models.Model):
    folder = models.ForeignKey(MovieFolder)
    name = models.CharField(max_length=500)
    inode = models.CharField(max_length=20, null=True, blank=True)
    size = models.PositiveIntegerField(null=True, blank=True)
    duration = models.PositiveIntegerField(null=True, blank=True)
    height = models.PositiveIntegerField(null=True, blank=True)
    width = models.PositiveIntegerField(null=True, blank=True)
    media_info = models.TextField(max_length=2000, null=True, blank=True)

    def __unicode__(self):
        return self.name

ying/forms.py
from django import forms

from ying.helper import get_tmdb_movie, save_movie
from ying.models import Movie, MovieFolder


class MovieFolderForm(forms.ModelForm):
    tmdb_id = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        instance = kwargs.get('instance')
        if instance and initial:
            initial['tmdb_id'] = instance.movie.tmdb_id

        super(MovieFolderForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(MovieFolderForm, self).clean()
        tmdb_id = cleaned_data.get("tmdb_id", "")
        if tmdb_id:
            try:
                movie = Movie.objects.get(tmdb_id=tmdb_id)
                cleaned_data['movie'] = movie
            except Movie.DoesNotExist:
                tmdb_movie = get_tmdb_movie(tmdb_id)
                if tmdb_movie:
                    movie = save_movie(tmdb_movie)
                    cleaned_data['movie'] = movie
        return cleaned_data

    class Meta:
        model = MovieFolder
        fields = ['name', 'inode', 'movie']

ying/views.py
import os

from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView
from taggit.models import Tag

from naszoo import settings
from ying.forms import MovieFolderForm
from ying.helper import scan_movie_folder
from ying.models import Movie, Category, MovieFolder


def movie_scan(request):
    scan_movie_folder(settings.MOVIE_ROOT)
    return redirect('/')


def folder_play(request, pk):
    movie_folder = MovieFolder.objects.get(pk=pk)
    folder = os.path.join(settings.MOVIE_ROOT, movie_folder.name)
    files = os.listdir(folder)
    videos = []
    subtitles = []
    for f in files:
        if f.lower().endswith('mp4'):
            videos.append(settings.STATIC_URL + settings.MOVIE_FOLDER + '/' + movie_folder.name + "/" + f)
        elif f[-3:].lower() in ('srt', 'ass'):
            subtitles.append(settings.STATIC_URL + settings.MOVIE_FOLDER + '/' + movie_folder.name + "/" + f)
    context = {'videos': videos,
               'subtitles': subtitles,
               'movie_folder': movie_folder}

    return render(request, 'ying/folder_play.html', context)


class FolderWithoutMovieListView(ListView):
    model = MovieFolder
    paginate_by = 20

    def get_queryset(self):
        return MovieFolder.objects.filter(movie__isnull=True)


class MovieFolderListView(ListView):
    model = MovieFolder
    paginate_by = 20

    def get_queryset(self):
        return MovieFolder.objects.order_by('name').filter(deleted=False)


class MovieFolderUpdateView(UpdateView):
    model = MovieFolder
    form_class = MovieFolderForm
    template_name = "ying/form_details.html"

    def get_success_url(self):
        return reverse('folder_without_movie')


class CategoryListView(ListView):
    model = Category


class CategoryUpdateView(UpdateView):
    model = Category
    fields = ['name', 'tmdb_id']
    template_name = "ying/form_details.html"


class MovieDetailView(DetailView):
    model = Movie


class MovieUpdateView(UpdateView):
    model = Movie
    fields = ['name', 'org_name', 'year', 'category', 'tags', 'summary']
    template_name = "ying/form_details.html"

    def get_success_url(self):
        return reverse('movies_exist')


class MovieDeleteView(DeleteView):
    model = Movie
    template_name = "ying/delete_confirm.html"

    def get_success_url(self):
        return reverse('movies_exist')


class MovieSearchListView(ListView):
    model = Movie
    paginate_by = 20
    template_name = 'ying/movie_list.html'
    only_downloaded = False
    q = None

    def get_queryset(self):
        tag_name = self.request.GET.getlist("tag_name", None)
        if not tag_name:
            tag_name = self.request.POST.getlist("tag_name", None)
        category_name = self.request.GET.getlist("category_name", None)
        if not category_name:
            category_name = self.request.POST.getlist("category_name", None)
        year = self.request.GET.get("year", None)
        if not year:
            year = self.request.POST.get("year", None)
        score_min = self.request.GET.get("score_min", None)
        if not score_min:
            score_min = self.request.POST.get("score_min", None)
        score_max = self.request.GET.get("score_max", None)
        if not score_max:
            score_max = self.request.POST.get("score_max", None)
        q = self.request.GET.get("q", None)
        if not q:
            q = self.request.POST.get("q", None)

        movies = Movie.objects.all()
        if self.only_downloaded:
            movies = movies.filter(id__in=MovieFolder.objects.all().values('movie'))

        if tag_name:
            movies = movies.filter(tags__name__in=tag_name)
        if category_name:
            movies = movies.filter(category__name__in=category_name)
        if year:
            movies = movies.filter(year=year)
        if score_min:
            movies = movies.filter(tmdb_score__gte=score_min)
        if score_max:
            movies = movies.filter(tmdb_score__lte=score_max)
        if q:
            movies = movies.filter(Q(name__contains=q) | Q(org_name__contains=q))
        return movies.distinct()

    def get_context_data(self, **kwargs):
        context = super(MovieSearchListView, self).get_context_data(**kwargs)
        tag_name = self.request.GET.getlist("tag_name", None)
        if not tag_name:
            tag_name = self.request.POST.getlist("tag_name", None)
        category_name = self.request.GET.getlist("category_name", None)
        if not category_name:
            category_name = self.request.POST.getlist("category_name", None)
        year = self.request.GET.get("year", None)
        if not year:
            year = self.request.POST.get("year", None)
        score_min = self.request.GET.get("score_min", None)
        if not score_min:
            score_min = self.request.POST.get("score_min", None)
        score_max = self.request.GET.get("score_max", None)
        if not score_max:
            score_max = self.request.POST.get("score_max", None)

        only_downloaded = self.request.GET.get("only_downloaded", None)
        if not only_downloaded:
            only_downloaded = self.request.POST.get("only_downloaded", None)

        if only_downloaded is not None:
            if only_downloaded in ['false', 'False', 'False', 'NO', 'no', 'No']:
                only_downloaded = False
            else:
                only_downloaded = bool(only_downloaded)
            self.only_downloaded = only_downloaded

        q = self.request.GET.get("q", None)
        if not q:
            q = self.request.POST.get("q", None)

        if tag_name:
            context['tag_name'] = tag_name
        if category_name:
            context['category_name'] = category_name
        if year:
            context['year'] = year
        if score_min:
            context['score_min'] = score_min
        if score_max:
            context['score_max'] = score_max
        if only_downloaded is not None:
            context['only_downloaded'] = only_downloaded
        if q is not None:
            context['q'] = q

        context['category_list'] = Category.objects.all()
        context['tag_list'] = Tag.objects.all()

        return context


class ExistMovieSearchListView(MovieSearchListView):
    only_downloaded = True


class MovieSearchGalleryListView(MovieSearchListView):
    only_downloaded = True
    template_name = 'ying/movie_list_g.html'

ying/templates/ying/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load staticfiles %}

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'ying/images/fire-ball_32.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'ying/images/fire-ball_64.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block head %}{% endblock %}

    <title>Ying</title>
</head>

<body>
<div style="display:none;" ><img src="{% static 'ying/images/fire-ball_256.png' %}" /></div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Ying</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="/movie/exist">Movies(Exist)</a></li>
                <li><a href="/movie/search">Movies(All)</a></li>
                <li><a href="/movie_folder">Folders(All)</a></li>
                <li><a href="/movie_folder/no_movie">Folders(NoMovie)</a></li>
                <li><a href="/movie_folder/scan">Scan Folder!</a></li>
                <li><a href="/category/">Categories</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/admin">Admin</a></li>
                <li><a href="/admin/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="content" class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

ying/templates/ying/category_list.html
{% extends "ying/base.html" %}

{% load thumbnail %}

{% block content %}

    {% load thumbnail %}

    <table class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>TMDB</th>
            <th>Count</th>
        </tr>
        {% for category in object_list %}
            <tr>
                <td>
                    <a href="/category/detail/{{ category.id }}">{{ category.id }}</a>
                </td>
                <td>
                    <a href="/movie/search?category_name={{ category.name }}">
                        {% if category.movie_set.all|length > 0 %}
                            {% thumbnail category.movie_set.all.0.poster "x100" crop="center" as im %}
                                <img src="{{ im.url }}"/>
                            {% endthumbnail %}
                            <br>
                        {% endif %}
                        {{ category.name }}
                    </a>
                </td>
                <td>
                    {{ category.tmdb_id }}
                </td>
                <td>
                    {{ category.movie_set.all|length }}
                </td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

ying/templates/ying/delete_confirm.html
{% extends "ying/base.html" %}

{% block content %}

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>

{% endblock %}

ying/templates/ying/folder_play.html
{% extends "ying/base.html" %}

{% load thumbnail %}
{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}

    {% for video in videos %}
        <video width="100%" controls poster="{{ movie_folder.movie.backdrop.url }}" preload="metadata">
            <source src="{{ video }}" type='video/mp4'>
            {% for subtitle in subtitles %}
                <track kind="captions" src="{{ subtitle }}" label="{{ subtitle }}" default>
            {% endfor %}
        </video>
    {% endfor %}

{% endblock %}

ying/templates/ying/form_details.html
{% extends "ying/base.html" %}

{% block content %}
    <form action="https://www.themoviedb.org/search" method="get" target="_blank">
        <input type="text" name="query">
        <button type="submit">Query TMDB</button>
    </form>


    <form action="" method="post">
        <table class="table table-striped table-hover">
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        {% if object %}
            <input type="submit" value="Update"/>
        {% else %}
            <input type="submit" value="Create"/>
        {% endif %}
    </form>
{% endblock %}

ying/templates/ying/movie_detail.html
{% extends "ying/base.html" %}

{% block content %}

    {% if object %}

        {% load thumbnail %}

        <div>
            <div>
                <a href="/movie/update/{{ object.id }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
                <a href="/movie/delete/{{ object.id }}" class="btn btn-primary"><span class="glyphicon glyphicon-remove"></span> Delete</a>
            </div>
            <table class="table table-striped">
                <tr>
                    <td>Name</td>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <td>Original Name</td>
                    <td>{{ object.org_name }}</td>
                </tr>
                <tr>
                    <td>Score</td>
                    <td>{{ object.tmdb_score }}</td>
                </tr>
                <tr>
                    <td>Poster</td>
                    <td>
                        {% thumbnail movie.poster "x100" crop="center" as im %}
                            <a href="{{ movie.poster.url }}"><img src="{{ im.url }}"/></a>
                        {% endthumbnail %}
                    </td>
                </tr>
                <tr>
                    <td>Backdrop</td>
                    <td>
                        {% thumbnail movie.backdrop "x100" crop="center" as im %}
                            <a href="{{ movie.backdrop.url }}"><img src="{{ im.url }}"/></a>
                        {% endthumbnail %}
                    </td>
                </tr>
            </table>
        </div>
        <div>
            {% for folder in object.moviefolder_set.all %}
                <div>
                    <div>Folder:
                        <a href="movie_folder/detail/{{ folder.id }}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a href="/movie_folder/play/{{ folder.id }}">
                            {{ folder.name }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% endif %}


{% endblock %}

ying/templates/ying/movie_list.html
{% extends "ying/base.html" %}

{% load thumbnail %}
{% load staticfiles %}

{% block content %}

    {% load thumbnail %}

    {% include "ying/query.html" %}

    {% include "ying/paginate.html" %}

    <script src="{% static 'ying/js/movie_list.js' %}"></script>

    <form action="#"></form>

    <div>
        <input type="checkbox" id="check_box_select"/>
        <button id="button_remove_selected"><span class="glyphicon glyphicon-remove"></span>Remove Selected</button>
        <button id="button_add_to_fav"><span class="glyphicon glyphicon-heart"></span>Add to Fav</button>
    </div>

    <table class="table table-condensed">
        <tr>
            <th>编号</th>
            <th>名称</th>
            <th>海报</th>
            <th class="visible-lg">剧照</th>
            <th class="hidden-xs">评分</th>
            <th class="hidden-xs">年份</th>
            <th class="hidden-xs" width="40">分类</th>
            <th class="hidden-xs" width="40">标签</th>
            <th class="hidden-xs">剧情</th>
        </tr>
        {% for movie in object_list %}
            <tr>
                <td>
                    <input type="checkbox" name="{{ movie.id }}" class="m_checkbox m_unchecked"/>
                    <a href="/movie/detail/{{ movie.id }}">{{ movie.id }}</a>
                </td>
                <td>
                    <a href="/movie/update/{{ movie.id }}">{{ movie.name }}</a>
                    <br>
                    {{ movie.org_name }}
                </td>
                <td style="position: relative;">
                    {% for movie_folder in movie.moviefolder_set.all %}
                        <a href="/movie_folder/play/{{ movie_folder.id }}">
                            <span style="font-size: 3em;position: absolute;top: 35px;left: 20px;z-index: 10;"
                                  class="glyphicon glyphicon-play"></span>
                        </a>
                    {% endfor %}
                    {% thumbnail movie.poster "x100" crop="center" as im %}
                        <img style="float: left;position: inherit;z-index: 1;" src="{{ im.url }}"/>
                    {% endthumbnail %}
                </td>
                <td class="visible-lg">
                    {% thumbnail movie.backdrop "x100" crop="center" as im %}
                        <img style="float: left;position: inherit;z-index: 1;" src="{{ im.url }}"/>
                    {% endthumbnail %}
                </td>
                <td class="hidden-xs">
                    {{ movie.tmdb_score }}
                </td>
                <td class="hidden-xs">
                    {% if movie.year %}
                        <a href="/movie/search?year={{ movie.year }}">{{ movie.year }}</a>
                    {% endif %}
                </td>
                <td class="hidden-xs">
                    {% for category in movie.category.all %}
                        <a href="/movie/search?category_name={{ category.name }}">{{ category.name }}</a>
                        <br>
                    {% endfor %}
                </td>
                <td class="hidden-xs">
                    {% for tag in movie.tags.names %}
                        <a href="/movie/search?tag_name={{ tag }}">{{ tag }}</a>
                        <br>
                    {% endfor %}
                </td>
                <td class="hidden-xs">
                    {{ movie.summary|truncatechars:80 }}
                </td>
            </tr>
        {% endfor %}
    </table>

    </form>

    {% include "ying/paginate.html" %}


{% endblock %}

ying/templates/ying/movie_list_g.html
{% extends "ying/base.html" %}

{% load thumbnail %}

{% block content %}
    {% include "ying/paginate.html" %}

    {% load thumbnail %}

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for movie in object_list %}
                {% if movie.poster %}
                    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}"></li>
                {% endif %}
            {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            {% for movie in object_list %}
                {% if movie.poster %}
                    {% if forloop.counter0 == 0 %}
                        <div class="item active">
                            <a href="{{ movie.poster.url }}">
                                {% thumbnail movie.poster "x400" crop="center" as im %}
                                    <img src="{{ im.url }}" width="100%">
                                {% endthumbnail %}
                            </a>
                        </div>
                    {% else %}
                        <div class="item">
                            <a href="{{ movie.poster.url }}">
                                {% thumbnail movie.poster "x400" crop="center" as im %}
                                    <img src="{{ im.url }}" width="100%">
                                {% endthumbnail %}
                            </a>
                        </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

{% endblock %}

ying/templates/ying/moviefolder_list.html
{% extends "ying/base.html" %}

{% load thumbnail %}

{% block content %}

    {% load thumbnail %}

    {% include "ying/paginate.html" %}

    <table class="table table-condensed">
        <tr>
            <th style="width: 2%">编号</th>
            <th style="width: 5%">目录名</th>
            <th style="width: 5%">电影</th>
            <th style="width: 5%">原名</th>
            <th style="width: 5%">年份</th>
            <th style="width: 7%">海报</th>
            <th style="width: 18%">剧照</th>
            <th style="width: 5%">分类</th>
            <th style="width: 5%">标签</th>
            <th style="width: 48%">剧情</th>
        </tr>
        {% for movie_folder in object_list %}
            <tr>
                <td>
                    <a href="/movie_folder/detail/{{ movie_folder.id }}">{{ movie_folder.id }}</a>
                </td>
                <td style="word-wrap: break-word">
                    <a href="/movie_folder/play/{{ movie_folder.id }}">
                        <span style="font-size:1.5em" class="glyphicon glyphicon-play"></span>
                    </a>
                </td>
                <td>
                    <a href="/movie/update/{{ movie_folder.movie.id }}">{{ movie_folder.movie.name }}</a>
                </td>
                <td>
                    <a href="/movie/update/{{ movie_folder.movie.id }}">{{ movie_folder.movie.org_name }}</a>
                </td>
                <td>
                    {% if movie_folder.movie.year %}
                        <a href="/movie/search?year={{ movie_folder.movie.year }}">{{ movie_folder.movie.year }}</a>
                    {% endif %}
                </td>
                <td>
                    {% thumbnail movie_folder.movie.poster "x100" crop="center" as im %}
                        <a href="{{ movie_folder.movie.poster.url }}"><img src="{{ im.url }}"/></a>
                    {% endthumbnail %}
                </td>
                <td>
                    {% thumbnail movie_folder.movie.backdrop "x100" crop="center" as im %}
                        <a href="{{ movie_folder.movie.backdrop.url }}"><img src="{{ im.url }}"></a>
                    {% endthumbnail %}
                </td>
                <td>
                    {% for category in movie_folder.movie.category.all %}
                        <a href="/movie/search?category_name={{ category.name }}">{{ category.name }}</a>
                        <br>
                    {% endfor %}
                </td>
                <td>
                    {% for tag in movie_folder.movie.tags.names %}
                        <a href="/movie/search?tag_name={{ tag }}">{{ tag }}</a>
                        <br>
                    {% endfor %}
                </td>
                <td>
                    {{ movie_folder.movie.summary|truncatechars:200 }}
                </td>
            </tr>
        {% endfor %}
    </table>

    {% include "ying/paginate.html" %}

{% endblock %}

ying/templates/ying/paginate.html
{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">

            <a class="btn btn-primary {% if not page_obj.has_previous %} disabled {% endif %} "
               href="?page=1{% if year %}&year={{ year }}&score_min={{ score_min }}&score_max={{ score_max }}{% endif %}{% for tag in tag_name %}&tag_name={{ tag }}{% endfor %}{% for category in category_name %}&category_name={{ category }}{% endfor %}">
                <span class="glyphicon glyphicon-fast-backward"></span>
            </a>
            <a class="btn btn-primary {% if not page_obj.has_previous %} disabled {% endif %}"
                    {% if page_obj.has_previous %}
               href="?page={{ page_obj.previous_page_number }}{% if year %}&year={{ year }}&score_min={{ score_min }}&score_max={{ score_max }}{% endif %}{% for tag in tag_name %}&tag_name={{ tag }}{% endfor %}{% for category in category_name %}&category_name={{ category }}{% endfor %}"
                    {% endif %}>
                <span class=" glyphicon glyphicon-backward"></span>
            </a>

            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            <a class="btn btn-primary
                {% if not page_obj.has_next %} disabled {% endif %} "
                    {% if page_obj.has_next %}
               href="?page={{ page_obj.next_page_number }}{% if year %}&year={{ year }}&score_min={{ score_min }}&score_max={{ score_max }}{% endif %}{% for tag in tag_name %}&tag_name={{ tag }}{% endfor %}{% for category in category_name %}&category_name={{ category }}{% endfor %}"
                    {% endif %} >
                <span class="glyphicon glyphicon-forward"></span>
            </a>
            <a class="btn btn-primary {% if not page_obj.has_next %} disabled {% endif %} "
               href="?page={{ page_obj.paginator.num_pages }}{% if year %}&year={{ year }}&score_min={{ score_min }}&score_max={{ score_max }}{% endif %}{% for tag in tag_name %}&tag_name={{ tag }}{% endfor %}{% for category in category_name %}&category_name={{ category }}{% endfor %}">
                <span class="glyphicon glyphicon-fast-forward"></span>
            </a>

        </span>
    </div>
{% endif %}